### ISSUE TITLE
Display the name of the note when /posted

### ISSUE THREAD

**Issue by KelseyHigham** [mazziechai/kose-kata#12]
it's easier to learn note names when the content is displayed alongside the note's name. 

i personally think a good spot for this is at the bottom, like `#6770a0 tptpt`

**Comment by mazziechai** [comment]
It's also possible to view the note name by viewing the command invocation by clicking on the command itself, but I'll add this.

**Comment by mazziechai** [comment]
This has been added in the latest commits.
